### ISSUE TITLE
Fehler bei Zuordnung der Dokumente zu Formatumstellungen [2410 statt 2504]

### ISSUE THREAD

**Issue by lgreif-hf** [Hochfrequenz/ahb-tabellen#101]
Wie kurz besprochen:
Zur Formatumstellung 2410 gibt es kaum aktualisierte Dokumente, namentlich (Filter 01.10.24 auf edi@energy):

AcknowledgementDocument AWT 1.0e
AcknowledgementDocument AWT - informatorische Lesefassung 1.0e
AcknowledgementDocument FB 1.0e
AcknowledgementDocument XSD 1.0e
ActivationDocument AWT 1.1c
ActivationDocument AWT - informatorische Lesefassung 1.1c
ActivationDocument FB 1.1c
ActivationDocument XSD 1.1c
Codeliste der Lokationsbündelstrukturen 1.0
Codeliste der Lokationsbündelstrukturen 1.0 Konsolidierte   Lesefassung mit Fehlerkorrekturen Stand: 12.12.2023
Codeliste der Lokationsbündelstrukturen - informatorische   Lesefassung 1.0
Codeliste der Lokationsbündelstrukturen - informatorische   Lesefassung 1.0 Konsolidierte Lesefassung mit Fehlerkorrekturen Stand:   12.12.2023
Kostenblatt AWT 1.0c
Kostenblatt AWT - informatorische Lesefassung 1.0c
Kostenblatt FB 1.0c
Kostenblatt XSD 1.0c
NetworkConstraintDocument AWT 1.1a
NetworkConstraintDocument AWT - informatorische Lesefassung 1.1a
NetworkConstraintDocument FB 1.1a
NetworkConstraintDocument XSD 1.1a
PlannedResourceScheduleDocument AWT 1.0d
PlannedResourceScheduleDocument AWT 1.0d Konsolidierte   Lesefassung mit Fehlerkorrekturen Stand: 10.06.2024
PlannedResourceScheduleDocument AWT - informatorische   Lesefassung 1.0d
PlannedResourceScheduleDocument AWT - informatorische   Lesefassung 1.0d Konsolidierte Lesefassung mit Fehlerkorrekturen Stand:   10.06.2024
PlannedResourceScheduleDocument FB 1.0d
PlannedResourceScheduleDocument XSD 1.0d
Regelungen zum Übertragungsweg 1.8
Regelungen zum Übertragungsweg für AS4 2.2
Stammdaten AWT 1.4
Stammdaten AWT - informatorische Lesefassung 1.4
Stammdaten FB 1.4
Stammdaten XSD 1.4
Unavailability_MarketDocument AWT 1.1a
Unavailability_MarketDocument AWT - informatorische Lesefassung   1.1a
Unavailability_MarketDocument FB 1.1a
Unavailability_MarketDocument XSD 1.1a

Folgende Dokumente sind erst ab 04.04.2025 gültig (Filter 04.04.25 auf edi@energy):
Allgemeine Festlegungen 6.1a
Allgemeine Festlegungen - informatorische Lesefassung 6.1a
Anwendungsübersicht der Prüfidentifikatoren 3.0
Anwendungsübersicht der Prüfidentifikatoren - informatorische   Lesefassung 3.0
APERAK / CONTRL AHB 2.4
APERAK / CONTRL AHB - informatorische Lesefassung 2.4
APERAK MIG 2.1i
APERAK MIG - informatorische Lesefassung 2.1i
API-Guideline 1.0
API-Guideline - informatorische Lesefassung 1.0
API-Webdienste zur Ermittlung der MaLo-ID der Marktlokation   1.0.0
Codeliste der Konfigurationen 1.3
Codeliste der Konfigurationen - informatorische Lesefassung 1.3
COMDIS AHB 1.0f
COMDIS AHB - informatorische Lesefassung 1.0f
COMDIS MIG 1.0e
COMDIS MIG - informatorische Lesefassung 1.0e
Entscheidungsbaum-Diagramme und Codelisten 4.0a
Entscheidungsbaum-Diagramme und Codelisten - informatorische   Lesefassung 4.0a
IFTSTA AHB 2.0f
IFTSTA AHB - informatorische Lesefassung 2.0f
IFTSTA MIG 2.0f
IFTSTA MIG - informatorische Lesefassung 2.0f
INVOIC / REMADV AHB 2.5d
INVOIC / REMADV AHB - informatorische Lesefassung 2.5d
INVOIC MIG 2.8d
INVOIC MIG - informatorische Lesefassung 2.8d
MSCONS AHB 3.1e
MSCONS AHB - informatorische Lesefassung 3.1e
MSCONS MIG 2.4d
MSCONS MIG - informatorische Lesefassung 2.4d
ORDCHG AHB 1.0
ORDCHG AHB - informatorische Lesefassung 1.0
ORDERS AHB 1.0
ORDERS AHB - informatorische Lesefassung 1.0
ORDERS MIG 1.4
ORDERS MIG - informatorische Lesefassung 1.4
ORDRSP AHB 1.0
ORDRSP AHB - informatorische Lesefassung 1.0
ORDRSP MIG 1.4
ORDRSP MIG - informatorische Lesefassung 1.4
PRICAT AHB 2.0e
PRICAT AHB - informatorische Lesefassung 2.0e
PRICAT MIG 2.0d
PRICAT MIG - informatorische Lesefassung 2.0d
QUOTES AHB 1.0
QUOTES AHB - informatorische Lesefassung 1.0
QUOTES MIG 1.3a
QUOTES MIG - informatorische Lesefassung 1.3a
Regelungen zum Übertragungsweg für API-Webdienste 1.0
REQOTE AHB 1.0
REQOTE AHB - informatorische Lesefassung 1.0
REQOTE MIG 1.3a
REQOTE MIG - informatorische Lesefassung 1.3a
UTILMD AHB Strom 2.0
UTILMD AHB Strom - informatorische Lesefassung 2.0
UTILMD MIG Strom S2.0
UTILMD MIG Strom - informatorische Lesefassung S2.0
UTILTS AHB Berechnungsformel 1.0g
UTILTS AHB Berechnungsformel - informatorische Lesefassung 1.0g
UTILTS AHB Definitionen 1.1b
UTILTS AHB Definitionen - informatorische Lesefassung 1.1b
UTILTS MIG 1.1d
UTILTS MIG - informatorische Lesefassung 1.1d

**Comment by OLILHR** [comment]
moved to https://github.com/Hochfrequenz/edi_energy_scraper/issues/230
