### ISSUE TITLE
Deeplinks to share

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/ahb-tabellen#11]
As a user I would like to share a link which already contains the information format version, pruefidentifikator and my search.

This makes it easy to provide needed information for others, e.g. in a ticket.

**Comment by JonasSchneegans** [comment]
@hf-krechan Ich habe die suche jetzt so angepasst, dass der Inhalt des Suchfeldes als query parameter in der url ist, also z.B. /ahb/FV2404/21030?query=testsuche. Passt das?
