### ISSUE TITLE
Add info text that mentions kohlrahbi and how to contact us for professional support

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/ahb-tabellen#141]
Die Website ist zwar öffentltich. Trotzdem wollen wir ein bisschen Werbung machen, dafür, dass man unsere Dienste als Hochfrequenz auch kaufen kann, also professionelle Beratung oder Support in MaKo-Fragen. Kriegen wir da einen schönen Text hin? Idealerweise mit verweis auf die landing page

**Comment by hf-kklein** [comment]
bei fragen bzgl inhalt bitte auf christian w. zugehen.

**Comment by hf-krechan** [comment]
hast du eine Vorstellung wo und wie das dargestellt werden soll?

**Comment by OLILHR** [comment]
ich denke man könnte den ganzen Text auf der start page stark reduzieren, das Banner noch etwas nach oben schieben und dann unten im Footer andere Tools und Services verlinken und knapp beschreiben.

<img width="1669" alt="Screenshot 2024-08-06 at 20 49 01" src="https://github.com/user-attachments/assets/34ea4d0a-8ffd-40cb-a3ec-c9ae338f0f5a">

das "Werbebanner" könnte ja z.B. wie der slide-in beim `bedingungsbaum` aussehen; 
vor allem vom Grafik-zu-Informationsgehalt-Verhältnis:

<img width="1274" alt="Screenshot 2024-08-06 at 20 59 51" src="https://github.com/user-attachments/assets/65f9ebd7-dddc-47b2-ad27-7366f676eab0">

**Comment by OLILHR** [comment]
es gab doch auch neue "Logos" von Annika für die einzelnen Tools/Services, oder? vielleicht lässt sich da auch ein "Standard" entwerfen, den wir wiederverwenden können, damit die HF-Lösungen etwas einheitlicher sind :)
