### ISSUE TITLE
For each expression that contains a number, add deep link to ahahnb

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/ahb-tabellen#169]
https://github.com/Hochfrequenz/AHahnB/pull/366
- [ ] find a good criteria on when to display a link (e.g. not for amodel mark like 'X'/'Muss'... alone but 'X [203]')
- [ ] the ahahnb base url should be configurable
- [ ] provide the query parameters `format`, `format_version` and `expression` as query params

**Comment by samarsrivastav** [comment]
hey @hf-kklein the link that you have provided is not working, Could you check it once !!

**Comment by hf-kklein** [comment]
@samarsrivastav thanks for your question. The link points to a private repository and a discussion there.

### What is AHahnB/Bedingungsbaum?

So what we want is:
* There is another Hochfrequenz website, internally named ahahnb. Its features is to visualize Expressions like they occur in the AHBs, for example an expression like `Muss [1] U ([2] O [3])` is visualized as a tree like this: 
![grafik](https://github.com/user-attachments/assets/49959ef5-c394-4dac-bf19-33afe5af1967)
* Now, if you also know from which EDIFACT format (say UTILMD, INVOIC...) and in which version used by German utilities this expression is meant (e.g. `FV2404` for all documents valid from April 2024 till end of September 2024), then you can also resolve, what is meant by the single tree nodes `[1]`, `[2]` and `[3]`.
* Example: If the expression is from a `format=COMDIS` AHB with `format_version=FV2404`, then the tree looks like this:
![grafik](https://github.com/user-attachments/assets/db0eae97-f180-4c51-8e22-94d78640c357)

The link to directly render this is:
```
https://bedingungsbaum.stage.hochfrequenz.de/tree/?format=FV2404&format_version=COMDIS&expression=Muss%20%5B1%5D%20U%20%28%5B2%5D%20O%20%5B3%5D%29
```

You need to create an account to use this service. Please note: It's only a test environment so far.

### The new feature for this project/repository:

The feature that I requested for ahbesser is is: In the column `Pflichtfeld-Kennzeichen` in ahbesser, add a deep link to ahahnb where the expression is non-trivial. Non-trivial means: no link shall be created for just 'Muss' or 'X'.

Check for example this AHB: http://ahb-tabellen.stage.hochfrequenz.de/ahb/FV2404/29001
It would be nice to have a link to ahahnb for this line and its expression:
![grafik](https://github.com/user-attachments/assets/45359171-5394-4547-9c8c-76f96dcba13f)

I want to click on `X (([939][21]) ∨([940][22])) ∧[508]` and be redirected to [`https://bedingungsbaum.stage.hochfrequenz.de/tree/?format=FV2404&format_version=COMDIS&expression=X%20%28%28%5B939%5D%5B21%5D%29%20%E2%88%A8%28%5B940%5D%5B22%5D%29%29%20%E2%88%A7%5B508%5D`](https://bedingungsbaum.stage.hochfrequenz.de/tree/?format=FV2404&format_version=COMDIS&expression=X%20%28%28%5B939%5D%5B21%5D%29%20%E2%88%A8%28%5B940%5D%5B22%5D%29%29%20%E2%88%A7%5B508%5D)

The base URL `https://bedingungsbaum.stage.hochfrequenz.de` has to be configurable via an environment variable. In this example, it refers to our staging/test environemnt.
