### ISSUE TITLE
Display Text/Date instead of _only_ Formatversion

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/ahb-tabellen#190]
instead of bare metal `FV2404` it'd be nice to have something like `April 2024 (FV2404)` or so in the UI dropdown

**Comment by hf-kklein** [comment]
similar to #160

**Comment by OLILHR** [comment]
since this is no meta information in the flatahb jsons, this has to be mapped manually, right?
```typescript
private getFormatVersionDate(formatVersion: string): string {
    const mapping: { [key: string]: string } = {
      'FV2104': 'April 2021 (FV2104)',
      'FV2110': 'Oktober 2021 (FV2110)',
      'FV2204': 'April 2022 (FV2204)',
      'FV2210': 'Oktober 2022 (FV2210)',
      'FV2304': 'April 2023 (FV2304)',
      'FV2310': 'Oktober 2023 (FV2310)',
      'FV2404': 'April 2024 (FV2404)',
      'FV2410': 'Oktober 2024 (FV2410)',
      'FV2504': 'April 2025 (FV2504)',
      'FV2510': 'Oktober 2025 (FV2510)',
      'FV2604': 'April 2026 (FV2604)',
      'FV2610': 'Oktober 2026 (FV2610)',
      'FV2704': 'April 2027 (FV2704)',
      'FV2710': 'Oktober 2027 (FV2710)',
      'FV2804': 'April 2028 (FV2804)',
      'FV2810': 'Oktober 2028 (FV2810)',
      'FV2904': 'April 2029 (FV2904)',
      'FV2910': 'Oktober 2029 (FV2910)',
      'FV3004': 'April 2030 (FV3004)',
      'FV3010': 'Oktober 2030 (FV3010)',
    };
```
which in turn means someone has to maintain this manually in 2031. is `April 2021 (FV2104)` sufficient? @hf-krechan

**Comment by hf-kklein** [comment]
Den Preis sind wir bereit zu zahlen :D du weißt heute ja gar nicht wann die nächsten Termine sein werden. 2019 zum Beispiel hatten wir ne formatumstellung im Dezember. Die hieß intern FV1912.

Tatsächlich ist es über viele Repos betrachtet ein nicht großer aber immer wieder auftretender Aufwand. Wir haben das für die Python Projekte in ein eigenes Mikropaket ausgelagert ("efoli") und für C# ist die Logik zentral in unserer EdiLibrary. (Speziell bei Python haben wir halt schon extrem viel Routine mit so Paketierung sodass der initiale overhead ok war). 

So maintainen wir pro Sprache im Backend nur einmal und dependabot übernimmt den Rest. Es geht ja viel um so stupide Logik: z.b aus einem Datum oder datetime die richtige FV zu berechnen oder auch prüfis auf Formate mappen. Nicht schlimm aber schon boilerplate.

Dann hast du aber immer noch Aufwände wenn z.B. dein frontend Formate/Versionen kennt die das BE (noch) nicht hat. Das kriegst du kaum abgefangen außer du liest die Optionen schon initial aus einem Endpunkt des backends.

**Comment by hf-kklein** [comment]
BTW: auch das haben wir drüben bei ahahnb schon implementiert. Kannste auch von dort kopieren

**Comment by OLILHR** [comment]
6 Jahre Puffer sollten also reichen 😄 https://github.com/Hochfrequenz/AHahnB/blob/main/src/services/ExpressionServices.ts

**Comment by hf-krechan** [comment]
we could also add the format version to the meta data. Aber der Ansatz mit der map ist erstmal fein :)

**Comment by OLILHR** [comment]
we would certainly have enough space
<img width="546" alt="Screenshot 2024-09-27 at 08 23 43" src="https://github.com/user-attachments/assets/832bfd89-72ff-44d1-aec0-3c3df511f6da">

i'm fine with both

**Comment by hf-kklein** [comment]
> 6 Jahre Puffer sollten also reichen

ich wette, dass ein user kommt und davon verwirrt ist was zu sehen, das weiter in der zukunft ist als 2025 ;)

**Comment by OLILHR** [comment]
> > 6 Jahre Puffer sollten also reichen
> 
> ich wette, dass ein user kommt und davon verwirrt ist was zu sehen, das weiter in der zukunft ist als 2025 ;)

da werden nur die Order angezeigt, die in machine-readable-ahbs liegen; das mapping ist nur präventiv, falls diese zukünftigen Verzeichnisse irgendwann mal angelegt werden.

oder meinst du den user der in den source code schaut? 😄
