### ISSUE TITLE
Selecting a Prüfidentifikator should trigger form submit

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/ahb-tabellen#191]
When 
* I select the prüfi from the dropdown
* or I typed 5 digits

it should directly submit the form an open the respective prüfidentifikator.

right now i need an additional enter or click although my intentions are clear. legacy ahbesser had this feature, too ;)

**Comment by OLILHR** [comment]
selecting a pruefi from the dropdown should trigger a refresh with the new table.
at least for me it does https://ahb-tabellen.stage.hochfrequenz.de/ahb
