### ISSUE TITLE
Visuelle Trennung der Datenelemente und Segmente

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/ahb-tabellen#203]
Lukas G. hat uns das Feedback gegeben, dass die Datenelemente und Segmente schwer zu unterscheiden sind.

Für die Anwender ist es hilfreich, wenn es eine visuelle Unterstützung gibt um die Trennungen zwischen Datenelementen und Segmenten deutlicher zu Kennzeichnen.

Als Inspiration kann man sich hier an den AHBs selbst orientieren.

![image](https://github.com/user-attachments/assets/1772f806-cbab-4a24-b302-9c5c5b74f3b8)

**Comment by OLILHR** [comment]
Lukas:
- [x] Trennung Segmentname (dicke Linie)
- [x] Trennung Datenelemente (gestrichelte Linie?)
