### ISSUE TITLE
Setup CI Pipeline to add AHB Documents into Azure Blob Storage

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/ahb-tabellen#21]
> [!IMPORTANT]  
> First we need the IAC setup before we can implement this CI pipeline.

The goal is to establish an automatic update process starting from the edu-energy-mirror repository.

A GH Action should run and upload the latest version of the scraped documents in the azure blob storage.

In the azure blob storage we want to keep the following directory structure:

```bash
|- FV2304
|- FV2310
    |- ...
    |- REQOTE
    |- UTILMD
        |- csv
        |- flatahb
        |- xlsx
    |- ...
|- FV2404
```

### Steps

- [x] Create Resource Group in Azure with pulumi
- [x] Add Azure Blob Storage to this Resource Group with pulumi
- [ ] Setup a GH Action in edi-energy-mirror which uploads the results of kohlrahbi into this Azure Blob Storage, see https://github.com/Hochfrequenz/edi_energy_mirror/blob/master/.github/workflows/kohlrahbi.yml
- [ ] Add "an azure resource" to run a Docker container

**Comment by hf-kklein** [comment]
why don't you sync the machine-readable_anwendungshandbuecher directly with the blob storage?

```mermaid
flowchart TD
    A("edi-energy-mirror:
    raw documents (PDF, docx)") -->|kohlrAHBi🥬| B("machine-readable-
    anwendungshandbücher")
    B -->|sync upload🔄| C("Azure Blob Storage")
    C <--> D("AHBesser
    (AHB tables)")
```

wouldn't this be easier as you could skip the repeated hour-long extraction with kohlrahbi which is done for the machine-readable-ahb repo already?

**Comment by hf-krechan** [comment]
Sounds absolute legit.
We can also follow your approach.

**Comment by hf-krechan** [comment]
The new approach is done in the [GitHub Action](https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher/blob/main/.github/workflows/upload-ahb-to-azure-blobstorage.yml) of the https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher repo
