### ISSUE TITLE
Put each condition into a new line

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/ahb-tabellen#234]
In the flatahb json files there are already newline characters like `\n`.

https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher/blob/843667045c76b1b58a82f4e6692061b83ca25b2b/FV2404/MSCONS/flatahb/13002.json#L1162

For a user the condition / Bedingung column is hard to read if there are many condition descriptions.

![image](https://github.com/user-attachments/assets/67ebf956-bc57-4882-a4a2-f21c13c671e4)

To improve the user experience each condition should start at a new line

**Comment by OLILHR** [comment]
added in #235
