### ISSUE TITLE
UI Verbesserungsvorschläge

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/ahb-tabellen#99]
Diese Änderungsvorschläge kommen von Annika S.

<img width="812" alt="image" src="https://github.com/Hochfrequenz/ahbesser/assets/68426071/ebd3506c-2426-4ff6-b0d3-0d285a9f1025">

**Comment by lgreif-hf** [comment]
Gehe mit allen Vorschlägen mit. Gerade auf dem Laptop verschwendet die große starre Kopfzeile sehr viel Platz.

**Comment by lgreif-hf** [comment]
Der Inhalt von Blau wäre cool in das (dann größere) Dropdownfeld einzufügen.
Also dass man dann sieht: PID Name [Sender > Empfänger] (evtl AHB)
Wenn es leicht umzusetzen ist, wären außerdem eventuell zwei Buttons neben dem PID-Feld praktisch, zum Springen zum vorigen und nächsten Prüfi!

**Comment by hf-krechan** [comment]
Claudia erwähnte noch den Wunsch, dass auch das Format (UTILMD, INVOIC, etc) auch als Information irgendwo dargestellt wird.

**Comment by lgreif-hf** [comment]
Anmerkungen Startseite:

**Comment by OLILHR** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/132905042/349062589-a3fd99d1-83f4-4d5e-8add-27fd52b1108b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMTA0NDIsIm5iZiI6MTcyMTIxMDE0MiwicGF0aCI6Ii8xMzI5MDUwNDIvMzQ5MDYyNTg5LWEzZmQ5OWQxLTgzZjQtNGQ1ZS04YWRkLTI3ZmQ1MmIxMTA4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwOTU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzI5MWRhYjk4YTQ5ZDY5MmM2ODY0OTI4N2RhNWRkOTAyZmNjODUzZmQyZDhlOGMxY2YxN2RiZDM1ODQ1MWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RrDHhtsDY5v4d0-SfzsSshjPR8MNUG1UGl3kbySn2RE)

Ich weiß nicht, ob das überhaupt zur Debatte steht, aber ich finde `Anwendungshandbücher für Menschen` hat was von "Bedienungsanleitung für Menschen" 😅 Und damit würde `Menschen` auf missverständliche Art und Weise im Vordergrund stehen; ich weiß zwar wie es gemeint ist, aber jetzt bekomme ich das nicht mehr aus dem Kopf und das könnte für andere ggf. ebenfalls die erste Assoziation sein.

ich fände sowas wie Anwendungs`FREUNDLICHE`Handbücher gut (farblich hervorgehoben oder so); ist tricky da was gutes zu finden.

**Comment by hf-krechan** [comment]
> Diese Änderungsvorschläge kommen von Annika S.
> 
> <img alt="image" width="812" src="https://private-user-images.githubusercontent.com/68426071/347396083-ebd3506c-2426-4ff6-b0d3-0d285a9f1025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTM2MzAsIm5iZiI6MTcyMTgxMzMzMCwicGF0aCI6Ii82ODQyNjA3MS8zNDczOTYwODMtZWJkMzUwNmMtMjQyNi00ZmY2LWIwZDMtMGQyODVhOWYxMDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA5Mjg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YzUzMGZlM2M2MDJmMDA0MzQxMTI4NGZkNTNhYjE3NzQxNTk1ZjM4NjJjZmQ2NGEyNzIyYTE4NmJmYjZjYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OB9Jv7Hsh39MVxuzLV3poQ2QZ_NkfuarctFxEqb5urg">

Annika M. und ich sind auch dafür, außer das redundante bleibt erstmal :)

**Comment by hf-krechan** [comment]
> Der Inhalt von Blau wäre cool in das (dann größere) Dropdownfeld einzufügen. Also dass man dann sieht: PID Name [Sender > Empfänger] (evtl AHB) Wenn es leicht umzusetzen ist, wären außerdem eventuell zwei Buttons neben dem PID-Feld praktisch, zum Springen zum vorigen und nächsten Prüfi!

Dass in dem Dropdown auch die Namen des Prüfis stehen ist eine gute Idee. Werden wir übernehmen.

**Comment by hf-krechan** [comment]
> Claudia erwähnte noch den Wunsch, dass auch das Format (UTILMD, INVOIC, etc) auch als Information irgendwo dargestellt wird.

Das Format wird unter Sender/Empfänger dargestellt.

**Comment by hf-krechan** [comment]
Das Ticket ist soweit bearbeitet. Ich schließe es daher.
Wenn es weitere UI/UX Anforderung gibt, dann macht dafür ein eigenes Issue auf.
